version: '3.1'

services:
  quarkus-app:
    container_name: quarkus-app
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: .

    ports:
      - "9090:9090"
      - "8080:8080"



  db:
    image: postgres
    container_name: postgres-qs
    restart: always
    environment:
      POSTGRES_PASSWORD: root123

    ports:
      - "15432:5432"


  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123

    ports:
      - "18080:80"
    depends_on:
      - db
